### ISSUE TITLE
Does not work with Python 3 and Django 1.9

### ISSUE THREAD

**Issue by alchemyx** [dancaron/Django-ORM#2]
I found your repo on stackoverflow, but unfortunately it does not work with Python 3 (missing parentheses on prints - nothing special), but then it shouts about missing SECRET_KEY:

Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from db.models import *
  File "/home/alchemyx/PycharmProjects/Django-ORM/db/models.py", line 10, in <module>
    class User(models.Model):
  File "/home/alchemyx/PycharmProjects/Django-ORM/db/models.py", line 11, in User
    name = models.CharField(max_length=255)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1072, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/conf/__init__.py", line 120, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

After filling it in in settings.py with some random string I get:

Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from db.models import *
  File "/home/alchemyx/PycharmProjects/Django-ORM/db/models.py", line 10, in <module>
    class User(models.Model):
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

So it seems that something has changed in Djano 1.9?

**Comment by wsqy** [comment]
https://github.com/wsqy/django-orm
I work it for support python3 and django1.10.2 @alchemyx @dancaron

**Comment by dancaron** [comment]
We have have Python 3 support.
